<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ksp</string>
	</array>
	<key>name</key>
	<string>KSP</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ksp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Tab stops like $1, $2...</string>
			<key>match</key>
			<string>\$(\d+)</string>
			<key>name</key>
			<string>keyword.ksp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ksp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Variables like $PARAM1, $TM_SELECTION...</string>
			<key>match</key>
			<string>\$([A-Za-z][A-Za-z0-9_]+)</string>
			<key>name</key>
			<string>keyword.ksp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ksp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Variables like $PARAM1, $TM_SELECTION...</string>
			<key>match</key>
			<string>\%([A-Za-z][A-Za-z0-9_]+)</string>
			<key>name</key>
			<string>keyword.ksp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ksp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Variables like $PARAM1, $TM_SELECTION...</string>
			<key>match</key>
			<string>\!([A-Za-z][A-Za-z0-9_]+)</string>
			<key>name</key>
			<string>keyword.ksp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(declare)</string>
			<key>name</key>
			<string>keyword.ksp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(:=|//*)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(on init|end on|on ui_control|on release)</string>
			<key>name</key>
			<string>support.constant</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(const|ui_label|ui_button|ui_switch|ui_slider|ui_menu|polyphonic)</string>
			<key>name</key>
			<string>support.constant</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(set_control_par_str|set_control_par|get_ui_id|move_control_px|make_persistent|set_control_help|read_persistent_var|set_script_title|in_range|set_key_color|set_listener|set_ui_height_px|message|make_perfview|add_menu_item|set_text|set_engine_par|hide_part|inc|SET_CONDITION|call|set_event_par|set_event_mark|play_note|get_event_par|ignore_event|dec|random)</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(if|end if|while|end while|else|select|end select|case)</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\$)(\{)([0-9]+):</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.ksp</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ksp</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>variable.complex.ksp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.ksp</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>comment.ksp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\(\$|\&gt;|\&lt;)</string>
			<key>name</key>
			<string>constant.character.escape.ksp</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ksp</string>
	<key>uuid</key>
	<string>05f3da6a-7acd-4ef4-b5d2-840d6325d250</string>
</dict>
</plist>
